### ISSUE TITLE
LESS loop function not compiling

### ISSUE THREAD

**Issue by allenwlee** [metaskills/less-rails-bootstrap#124]
I'm at a loss for what is happening and wanted to reach out here, in case it is related to this gem.  The following code below is not being compiled.  I am using `rails 4.2.0`, `ruby 2.0.0`, and  `less-rails-bootstrap (3.0.2)`.  As an aside, I can't update to a later version due to an issue with the latest Bootstrap release.

    @action-color:  #00ffff;  //aqua 
    @adventure-color: #000000;  //black
    @animation-color: #0000ff;  //blue 

    .genre-names(
       ~"action",
       ~"adventure",
       ~"animation";
     );
    .genre-names(@list, @index: 1) when (isstring(extract(@list, @index))) {
            @genre: extract(@list, @index);

           .@{genre} {
           background-color: ~'@{@{genre}-color}';
        }
        .genre-names(@list, (@index + 1));
    }

There are more details in my [stackoveflow post here](http://stackoverflow.com/questions/29424346/less-loop-function-not-compiling-in-rails)

Any help appreciated.

**Comment by simi** [comment]
I think this not related to `less-rails-bootstrap`. Can you test this with just `less-rails` gem  and with `less.rb` gem only?

**Comment by lacostenycoder** [comment]
I follow all instructions for custom instructions for *= require custom_bootstrap/custom_bootstrap
but I keep getting " undefined method `[]' for nil:NilClass "

App trace:

app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb___3322370523267408108_70293595692240'

what am i doing wrong?

**Comment by maxd** [comment]
This problem marked as answered on SO. I think need to close it.

**Comment by allenwlee** [comment]
yes, thanks @maxd @simi . apologies for not following up sooner.  I found that `less-rails-bootstrap v 3.0.2`, which I have to keep, uses `less-rails v1.3.3` which is outdated.  FYI, I have to keep this old version of `less-rails-bootstrap` because of a very annoying backwards-compatibility caused by bootstrap 3.0 to 3.2, described [here](https://github.com/twbs/bootstrap/issues/14314) for the morbidly curious.
