### ISSUE TITLE
Issue with asset pipeline

### ISSUE THREAD

**Issue by lacostenycoder** [metaskills/less-rails-bootstrap#127]
I follow all instructions for custom instructions for *= require custom_bootstrap/custom_bootstrap
but I keep getting " undefined method `[]' for nil:NilClass "

App trace:

app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_html_erb___3322370523267408108_70293595692240'

what am i doing wrong?

**Comment by simi** [comment]
@lacostenycoder: can you try `sprockets3` branch please?

try this in your Gemfile:
```ruby
gem 'less-rails-bootstrap', github: 'metaskills/less-rails-bootstrap', branch: 'sprockets3'
```

**Comment by lacostenycoder** [comment]
Vioala!  That works thanks!

**Comment by simi** [comment]
This branch will be merged into master and released really soon. Thanks for testing!

**Comment by lacostenycoder** [comment]
It worked fine a a new rails test app, but I can't seem to track down a
problem I'm having now on an existing app.

Here are my settings:

https://gist.github.com/lacostenycoder/59482c41fb8ca4fc6a0e

Error now is:

Less::ParseError at /
error evaluating function `asset-url`: undefined method `start_with?' for
nil:NilClass

_app_views_layouts_application_html_erb___3797070218055661598_70306713729420
 app/views/layouts/application.html.erb, line 7
