### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by hlascelles** [metaskills/less-rails-bootstrap#135]
Hi @metaskills,

Is this gem still maintained? There are PRs for newer versions of Rails / bootstrap etc but the build pipeline seems to be failing and nothing has been merged for 5 years. Do you need a new maintainer?

**Comment by simi** [comment]
I'm around to help, but I think it would be better to recommend to not use this for new/maintained projects in README. LESS seems abandoned (at least in Ruby world) at all.

All less ruby infrastructure related to this project for example relies on https://github.com/cowboyd/less.rb which seems unmaintained as well.

Also bootstrap doesn't provide less variant anymore AFAIK.

**Comment by hlascelles** [comment]
OK, yes, I see what you mean. Will go for the transition to SASS. Thanks! :+1:
